"""
Semantic layer — the business context that makes the agent's SQL CORRECT.
Assembled into the system prompt: schema + join map + business rules + gotchas +
worked examples. This is what turns "text-to-SQL" into "text-to-RIGHT-SQL".
"""
from __future__ import annotations
from app.ai import warehouse

# ── Business rules (the definitions an analyst must know) ───────────────────
RULES = """BUSINESS DEFINITIONS (use these exactly):
• Currency: format as ₹Cr (crore = 10,000,000) and ₹L (lakh = 100,000). 1 Cr = 100 L.
• Window: all sales / purchase / consumption data is concentrated in a 6-month core window (Dec-2025 … May-2026) — treat this as THE window for any windowed total. Procurement/GRN-side tables (fact_po, fact_grn, kpi_cycle_time) also carry a much thinner tail of records through Dec-2026 (well under 5% of rows for any given vendor/plant) — if a query surfaces those months, they're real but low-volume, not a sign the "6 months" framing is wrong; don't average them into a trend on equal footing with the core months without noting the far smaller sample. Inventory & expiry are an as-on SNAPSHOT dated 2026-05-31.
• "Sales" / "revenue" ALWAYS means the billed pharmacy sales in the sales_* tables (sales_totals, sales_by_material, sales_by_manufacturer, sales_by_hospital, sales_by_material_*, sales_monthly). margin = revenue − cost. margin_pct = margin / revenue * 100. REAL billed IP+OP revenue with true margin (billed MRP − actual cost). CANONICAL TOTAL: for an OVERALL revenue/margin figure use sales_totals (SUM over its IP+OP rows) — the authoritative company total (₹521.67 Cr); sales_by_material sums to the same. Do NOT take an overall total from sales_by_manufacturer — it UNDERCOUNTS ~0.4% (materials with no manufacturer mapping drop out); use it ONLY for a by-manufacturer breakdown.
• ⚠️ forecast_sales is NOT billed sales. It is the demand-FORECAST model's own series — sparse and on a different scale (its sales_quantity/sales_value total only ~₹67 Cr vs the real ₹521 Cr). NEVER use forecast_sales (or its sales_quantity/sales_value columns) to answer a "sales"/"revenue" question — those come only from the sales_* tables above. Use forecast_sales ONLY for demand/forecast questions (predicted demand, cashflow forecast, forecast vs actual).
• Procurement margin is only a PROXY: on OUTLIER-CLEAN fact_grn rows (see gotcha #15 — same net_price>=10 + 8x-band + n>=5 rule applies here too, since unit_mrp is exactly as prone to data-entry errors as net_price), mrp_value = gr_qty*unit_mrp, cost_value = gr_qty*net_price, margin_pct = (mrp_value−cost_value)/mrp_value — the denominator is ALWAYS mrp_value, never spend/total_amount_wo_tax (dividing a margin by the wrong, much-smaller denominator produces a nonsensical 5-or-6-digit "percentage"). Call it "MRP-proxy margin", never billed margin.
• CANONICAL "total procurement spend" (the figure the actual Procurement dashboard shows, ₹649.91 Cr) = SUM(kpi_purchase_value.purchase_value) — this KPI aggregate is actually PO-ORDER-value based (it matches fact_po.total_value_wo_tax almost exactly). Use it for any overall/portfolio spend total so the AI's answer matches the dashboard. fact_grn.total_amount_wo_tax (₹478.27 Cr) is a DIFFERENT, narrower metric — goods ACTUALLY RECEIVED/receipted so far, always lower than ordered value — only use it if the user specifically asks about received/GRN value, landed cost, or receipt timing, never for a generic "total spend" question.
• Days of cover (DOH) = kpi_doh.doh_days; report the MEDIAN over rows where doh_days>0 (the mean is skewed by overstock — never report the mean). In prose call it the "median" or "typical" days of cover — do NOT call it the "average" (a median is not an average). This applies to any metric where you use a median.
• Expiry: compute days-to-expiry as date_diff('day', DATE '2026-05-31', expiry_date) on fact_inventory (qty>0, expiry_date not null). Bands: Expired (<0), 0-30, 31-90, 91-180, 181-365, 365+. "Near-expiry / actionable" = Expired + everything ≤180 days.
• Manufacturer lives in dim_material.manufacturer_desc (join on material) and in sales_by_manufacturer / sales_by_material_mfr for revenue.
• Department: in THIS dataset there are NO readable department names — dim_costcenter.department_name and kpi_consumption_by_department.department_name are both just the cost-centre CODE (a number like '1080101005'). Group consumption by cost_ctr and present it as "Cost centre <code>"; do NOT imply a named department exists. Treat cost_ctr as a text label, never a numeric value.
• Category = material_group (codes like 'M065-INJECTIONS', 'M113-TABLETS') — strip the 'M###-' prefix and Title-Case for display. This is what "category"/"injections"/"tablets"/"which category" ALWAYS means. dim_material also has major_group_desc/minor_group_desc — those are a DIFFERENT thing: the drug's pharmacological/therapeutic CLASS (e.g. 'TAXANE', 'MONOCLONAL ANTIBODY (EGFR)', 'ANTIANDROGEN') and molecule detail. Never filter major_group_desc for a physical-form category like "injections" — it holds drug-class names, not 'Injections'/'Tablets', and will silently match zero rows.
• "Pharma" / "pharmaceutical" / "drug" = dim_material.material_type IN ('ZNOC-Medical Non Onco Drugs', 'ZOC-Medical Onco Drugs'). Everything else (ZMC-Medical Consumables, ZNMC-Non Medical Consumables, ZLR-Laboratory Reagents, ZMA/ZNMA-Assets, lab calibrators/controls) is NOT pharma — it's equipment, consumables, or reagents. ~27% of the catalog has material_type=NULL (unclassified) — mention that coverage gap if it's relevant to the answer. Never guess a different filter for "pharma" — this is the one to use.
• "Critical" / "life-saving" / "essential" medicine has NO defined column anywhere in this data — not formulary, not material_type, not dosage form. Never invent a proxy for it (e.g. treating injectable dosage form as "critical", or tablets as "not critical") — call ask_clarification to find out what they actually mean (a named drug/class, the formulary field, high-value oncology drugs, etc.) instead of silently guessing a filter.
• There is no revenue/margin data linked to VENDOR — procurement (fact_po/fact_grn/kpi_purchase_value) is not joined to the sales_* tables, so "margin by vendor" / "which vendor has the best margin" is NOT computable from this data. If asked, say so plainly and offer what vendors DO have instead: spend (kpi_vendor_volume), lead time (kpi_vendor_lead_time). Never invent a formula for vendor margin (e.g. purchase_value − purchase_qty*(purchase_value/purchase_qty) is algebraically always zero) and never silently substitute spend for margin without saying that's what you did."""

# ── Which table for what + join keys ────────────────────────────────────────
GUIDE = """TABLE GUIDE (pick the right source):
REVENUE / MARGIN (billed sales, 6mo):
  sales_by_manufacturer(manufacturer, revenue, cost, qty)          — revenue/margin by manufacturer
  sales_by_hospital(hospital, revenue, cost, qty)                  — by billing hospital (23 hospital codes)
  sales_by_material(material, material_desc, material_group, revenue, cost, qty)     — by product (6-MONTH TOTAL, no month column)
  sales_by_material_mfr(manufacturer, material, material_desc, material_group, …)    — product×manufacturer (mfr drill)
  sales_by_material_hospital(hospital, material, material_desc, material_group, …)   — product×hospital (hospital drill)
  sales_monthly(patient['IP'|'OP'], month, revenue, cost, qty)     — WHOLE-COMPANY monthly revenue; ONLY columns are patient/month — it has NO material/manufacturer/category/hospital column, so it can NEVER be filtered or attributed to any specific item, brand, category or hospital. Use ONLY for the overall monthly revenue trend or the IP-vs-OP split.
  sales_totals(patient, revenue, cost, qty)                        — grand totals by IP/OP (canonical overall revenue = SUM of these rows)
INVENTORY (snapshot 2026-05-31):
  kpi_stock_value(plant, material, material_desc, material_group, stock_qty, stock_value_cost, stock_value_mrp)
  kpi_doh(plant, material, material_group, stock_qty, avg_daily_consumption, doh_days)
  kpi_aging_distribution(plant, material_group, aging_bucket, stock_value, sku_count)
  kpi_non_moving(material, material_desc, material_group, closing_stock_value, aging_days, last_sale_date, reason)
  kpi_health_score(material, material_group, closing_stock_value, health_score, health_tier, turnover_annualized)
  fact_inventory(plant, material, material_desc, batch, qty, total_cost, total_mrp, manufacturer_desc, material_group, expiry_date, snapshot_date)  — batch/expiry grain
  kpi_near_expiry(material, material_desc, batch, expiry_date, days_to_expiry, expiry_bucket, qty, total_cost)  — capped ≤180d; for full ladder use fact_inventory
PROCUREMENT:
  ⭐ mart_procurement — PREFER THIS for any procurement PRICE / vendor / per-unit / overpay / "who is cheapest" / price-outlier question. It is fact_grn already CLEANED and ENRICHED, one row per receipt line, so you don't have to re-derive the outlier-clean two-pass or the vendor-lead-time join by hand. Columns: plant, material, material_desc, category[=clean material_group], material_type, manufacturer_desc, vendor_name, qty, unit_price[per-unit net price], unit_mrp, line_value, is_capex_or_service[bool — TRUE = construction/service/AMC line, NOT a stocked item], material_median_price[outlier-cleaned median for this material], material_price_sample_n[how many clean rows back that median], is_price_outlier[bool — TRUE = this line's price is outside the 8x band, a likely data-entry error, EXCLUDE it from price analysis], vendor_avg_lead_time_days, vendor_median_lead_time_days[lead time PRE-JOINED — never join kpi_vendor_lead_time by hand], gr_date, year, month, month_num.
  mart_material_price_stats(material, material_desc, category, clean_median_price, clean_n, raw_n, raw_min_price, raw_max_price, has_price_outlier, price_is_stable[clean_n>=5]) — one row per material; the definitive clean price of an item. For a single-item "what's the price of X" use clean_median_price (report raw_n records even if price_is_stable is false — never refuse a lookup just because clean_n<5).
  mart_material_vendor_price_stats(material, material_desc, category[=clean material_group], vendor_name, clean_median_price, clean_n, total_qty, total_value, price_is_stable[clean_n>=5]) — one row per material×vendor; use for "which vendor is cheapest for item X" and for a category-scoped vendor comparison (filter category = 'M065-INJECTIONS' etc — NEVER filter injections via material_desc ILIKE '%injection%', which matches only stationery like an INJECTION REGISTER, not the drug category). ⛔ For any "best price" / "savings if we switch vendor" ranking, ONLY compare vendors where price_is_stable (clean_n>=5) — a vendor with 2-3 lines at a suspiciously low price is a data-entry/one-off outlier, NOT an achievable price, and treating it as a scalable saving is a classic embarrassing error.
  fact_grn(plant, material, vendor_name, po_no, gr_qty, net_price, unit_mrp, total_amount_wo_tax, major_group[raw, messy — see gotcha below], gr_date)  — actual receipts & prices (255k rows). Use the raw table only for received-VALUE/receipt-timing questions; for anything about PRICE use mart_procurement instead.
  fact_po(plant, material, material_desc, vendor_name, po_no, po_qty, open_qty, net_price, total_value_wo_tax, major_group[raw, messy], po_date, year, month)  — orders; open_qty>0 = open PO
  kpi_monthly_purchase_value(year, month, plant, material, material_desc, material_group, monthly_purchase_value, purchase_qty)  — PER-MATERIAL monthly purchase trend (use this for an item's spend over time)
  kpi_purchase_value(plant, vendor_name, category, year, month, purchase_value, purchase_qty)  — by vendor/category, not per-material; category is a RAW freeform field, NOT material_group (see gotcha #20). ⛔ This table has NO material/material_type column at all — it CANNOT be filtered by "pharma", "injections", "tablets", or any dosage-form/drug-class term. NEVER use kpi_purchase_value for a "pharma spend" / "injection spend" / "<category> spend" question that needs a material-type or physical-category filter — use fact_po or kpi_monthly_purchase_value JOINed to dim_material instead (both carry material + material_group, and fact_po's material additionally lets you join dim_material.material_type for pharma). Reserve kpi_purchase_value only for a plain vendor-spend or vendor×category (its own raw category, unfiltered) question.
  kpi_vendor_volume(plant, vendor_name, vendor_value, value_share_pct)  — per plant; SUM by vendor_name for portfolio
  kpi_vendor_lead_time(vendor_name, avg_lead_time_days, median_lead_time_days)
CONSUMPTION:
  kpi_units_consumed(year, month, plant, material, material_group, total_units, consumption_cost)
  kpi_consumption_by_department(plant, cost_ctr, department_name, month, consumption_qty, consumption_cost)
  fact_consumption(material, plant, cost_ctr, qty, amount_lc, posting_date, month)  — line grain
FORECAST / RISK:
  stock_replenishment_and_aging_risk(plant, material_id, material_desc, material_group, closing_stock, demand_monthly, replenishment_quantity, aging_risk)  — replenishment_quantity>0 = reorder
  kpi_stock_radar(plant, material_id, material_desc, closing_stock, demand_forecast, coverage_months, radar_status)
  kpi_fulfillment(plant, material_id, closing_stock, demand_monthly, fulfillment_rate, coverage_months)
  forecast_sales(material_id, plant, material_group, posting_date, sales_quantity, sales_value, sales_quantity_forecast, cashflow_forecast)  — actual+forecast monthly
DIMENSIONS (join keys):
  dim_material(material → material_desc, material_group[physical category, e.g. 'M065-INJECTIONS'], manufacturer_desc, generic_name, major_group_desc[drug CLASS e.g. 'TAXANE' — NOT a category filter])
  dim_vendor(vendor_code → vendor_name)   dim_plant(plant → plant_name)   dim_costcenter(cost_ctr → department_name)
  dim_sloc(plant, sloc → sloc_desc, ip_op_class[IP/OP/OT/OTHER ward type])  — ⚠ COMPOSITE KEY: join on plant AND sloc TOGETHER, never sloc alone (see gotcha #24)

JOIN KEYS: material (universal — bridges sales/inventory/procurement/consumption to dim_material for manufacturer/generic/category); vendor_name; plant; cost_ctr; po_no (grn↔po).
NOTE: 'material' in sales/kpi tables == 'material' in dim_material == 'material_id' in the risk/radar/fulfillment tables."""

# ── Gotchas that cause WRONG answers ────────────────────────────────────────
GOTCHAS = """CRITICAL GOTCHAS (ignore these and the numbers are wrong):
1. sales_* tables have NO plant/region column — they are hospital-based (23 hospitals ≠ the plant codes). Don't try to filter sales by plant.
2. Inventory/procurement KPI tables are per (plant × material). For a PORTFOLIO number, SUM across plants — don't report a single plant's row.
3. kpi_vendor_volume has one row per vendor×plant — SUM vendor_value GROUP BY vendor_name before ranking vendors.
4. ⛔ MEAN-OF-RATIO TRAP (general — not just DOH): any per-entity RATIO (doh_days, cost-per-unit-consumed = amount_lc/qty, variance_pct, growth_pct, fill_rate_pct, etc.) can be blown up by a near-zero denominator on a single entity, or by averaging across entities with wildly different bases. For a PORTFOLIO figure, report the MEDIAN over rows where the ratio is defined and positive (e.g. MEDIAN(doh_days) WHERE doh_days>0, never AVG — DOH's mean is ~1445d nonsense from the overstock tail, median ≈121d), or recompute from SUM(numerator)/SUM(denominator) rather than AVG(a precomputed ratio column) — this matters most when entities (plants/vendors/materials) have very different bases (a 50-plant AVG(variance_pct) can be dominated by one tiny-base plant whose spend went ₹5,000→₹5,30,000 — a 10,508% "variance" that swamps a true ~11% portfolio change). This ALSO applies to a single-item or item-level RANKING, not just a portfolio average: a material with near-zero avg_daily_consumption or near-zero qty can show a per-unit ratio (DOH days, cost-per-unit-consumed) in the hundreds of thousands — arithmetically correct, but not a real finding. Before presenting a "highest DOH" / "most expensive per unit consumed" item-level result, sanity-check the denominator isn't near-zero, and if you still show an extreme value, caveat it as likely a near-zero-denominator artifact rather than presenting it as straightforward overstocking or cost.
5. Purchases-by-MANUFACTURER via dim_material.manufacturer_desc covers only ~18% of purchase VALUE (master is sparse for high-value items) — if asked, compute it but STATE the coverage caveat. Manufacturer on the REVENUE side (sales_by_manufacturer) is clean.
6. month is a text label ('December','January',…) in EVERY table that has one, with NO exception — kpi_procurement_variance, kpi_monthly_purchase_value, kpi_units_consumed, kpi_cycle_time, all of them. To sort chronologically use a CASE/ordering, not alphabetical, no matter which table you're querying. Prefer sales_monthly.month which is 'YYYY-MM' when the question is about revenue.
7. Always round money to ₹Cr/₹L in the FINAL answer, but keep raw values in SQL for correctness.
8. ⛔ GRAIN IS LAW (the single most important rule). The DIMENSIONAL MODEL section lists, for EVERY table, exactly which dimensions it can be sliced by and whether it has a time axis. A number is only about an entity if the query that produced it actually GROUPed/filtered a table that carries that dimension. So: (a) only filter/GROUP BY a column in that table's "slice by" list; (b) only show a month/period trend from a table whose "time axis" is not NONE; (c) if the breakdown the user wants needs a dimension crossed with a time axis that DON'T co-exist in any single table, that exact breakdown is NOT AVAILABLE — do NOT approximate it by taking a broader table's numbers and relabelling them to the narrower scope (that is a confident factual error). Give the closest correct cut the model DOES support and say plainly what isn't available. (Illustrative trap: a specific item's month-by-month SALES — no table carries item AND a sales time axis, so report the item's TOTAL sales, and if useful its monthly PURCHASES/CONSUMPTION which DO exist per item×month, each clearly labelled as purchase/consumption — never as sales.)
9. dim_material is the full CATALOG — many SKUs have ZERO transactions (no sales, no purchases). If an item returns no rows in the fact tables, DON'T call it a technical error: say plainly it has no recorded sales/purchases in this 6-month window, and offer its sibling SKUs (same generic_name or material_group that DO have activity, e.g. via dim_material) so the question isn't a dead end.
10. Column names are already clean — use material_desc / material_group (never a bare `desc` or `group`; those reserved words have been aliased away). Just write plain identifiers.
11. NAME LOOKUPS: a product's brand name (e.g. 'CALPOL', 'AUGMENTIN') lives in material_desc. To find a named item, filter material_desc ILIKE '%name%'. generic_name is the MOLECULE ('PARACETAMOL','TRAMADOL') — use it only to group products by active ingredient, NEVER to search for a brand. When the user quotes an item that returns nothing, try a looser material_desc ILIKE on the distinctive word (e.g. 'CALPOL') before concluding there's no data — the exact SKU string ('CALPOL-T TAB') may not exist even though the brand family does.
12. dim_material (24,931 SKUs) is the FULL multi-year item master; sales/PO/GRN/consumption only cover the 6-month analytics window, so most catalog SKUs (~57%) show zero rows there — that alone is not newsworthy. Before telling a user an item "has no data", ALWAYS also check fact_inventory (physical on-hand snapshot, which can hold batches received before the window even started) and fact_consumption. If it HAS inventory, that's the real story — report qty, aging_days, expiry_date (vs snapshot 2026-05-31 — flag if already expired) and formulary status (dim_material.formulary / fact_inventory.formulary: 'OUT OF FORMULARY' often explains why an item stopped moving). A catalog item with stock but no sales/purchase in-window is classic DEAD / NON-MOVING stock — say so plainly instead of a flat "no data".
13. aging_days (kpi_non_moving, fact_inventory) = age of the BATCH since it was received (GRN date), NOT days since last sale. "Non-moving" means ZERO consumption in the 6-month window regardless of how new the batch is — so a freshly-received batch (low aging_days) can still be non-moving. When reporting non-moving stock, lead with the value and the "no consumption in 6 months" reason; if you mention aging_days, call it "batch age", never imply it's time-since-last-sale (that would read as self-contradictory).
14. Reorder / stockout-risk tables (stock_replenishment_and_aging_risk, kpi_stock_radar, kpi_fulfillment) span ALL materials including non-clinical consumables (stationery, kitchen, housekeeping — material_group like 'Stationary'/'Kitchen'). By raw coverage these often top the list. If the top results are non-medicine, SAY SO and, unless the user asked broadly, either focus on drug categories or offer a medicine-only view — a hospital operator asking about "items to reorder" usually means clinical supplies.
15. ⛔ PRICE/RATE OUTLIERS ARE REAL AND COMMON in ANY per-material price or cost-rate column — this is not unique to fact_grn/fact_po. fact_grn/fact_po net_price: 2.8% of materials (668 of 23,955) show a >20x spread from data-entry mistakes: near-zero placeholder prices (₹0.01), price↔qty transposition (one line has price=1/qty=54140, another price=54140/qty=1 for the SAME material/date/vendor), or unit-of-measure inconsistency (one line ₹62 for a milk packet, another ₹40,000 for "1 unit" of the same SKU). fact_consumption's amount_lc/qty ("cost per unit consumed") has the identical failure mode — a single material can swing >1,000,000x across its own lines (e.g. ₹0.01/unit on one line, ₹10,000+/unit on another, same material). unit_mrp is exactly as prone to the same errors as net_price. A raw MIN/MAX/median-deviation query WILL surface these as a fake multi-crore "impact" for an ordinary low-value item — this is the single most likely way to hand a client an absurd, embarrassing number. For ANY overpay / price-deviation / price-swing / "biggest price increase" / "most expensive per unit consumed" / MRP-proxy-margin analysis THAT RANKS OR AGGREGATES ACROSS MANY MATERIALS, ALWAYS: (a) filter the price/rate column >= 10 (kills placeholder prices — apply the same floor to unit_mrp/amount_lc-per-unit if the calc uses it); (b) compute a material's median from ALL its clean rows, THEN drop rows where the value is outside median/8..median*8 (kills transposition/UOM errors — genuine price variance is rarely beyond an 8x band); (c) require at least 5 remaining rows per material before ranking it (a 1-2 line "impact" is not a stable finding). Never skip this — it is exactly what turns a nonsense ₹146 Cr result for a single screw into the honest, defensible answer (a clean top-10 in the ₹1-3 Cr range). If asked, you can mention that some rows were excluded as likely data-entry errors — that is itself a useful, honest finding to hand the client, not something to hide.
   ⚠ The n>=5 threshold above is for a RANKING/aggregate-impact question (many materials competing for a "top" spot) — it is NOT a reason to refuse a SINGLE, specifically-named item's price lookup. For "what's the price of <named item>", apply the same clean-band logic (a)/(b) to that item's own rows if it has several, but if it only has 1-4 rows total, report the median/typical of whatever exists with a brief "based on N purchase records" caveat — never respond that the price "could not be determined" just because it falls under the ranking threshold.
16. price_deviation_impact / overpay style metrics should be reported as an UNSIGNED magnitude (SUM(ABS(price - median)*qty)) — "how much this item's pricing swung, cost-wise" — consistently across every phrasing of the question (top-N ranking, min/max breakdown, single-item lookup). Do not switch to a signed formula (price - median without ABS) in a follow-up on the same topic — that flips the sign and looks like a contradiction of your own earlier answer for the same item.
17. ⛔ ANY RATIO/PERCENTAGE (margin_pct, growth %, X/Y*100) needs its DENOMINATOR filtered > 0 in the SQL — a row where both sides of the ratio are 0 (e.g. a manufacturer/vendor/category with zero recorded revenue AND zero cost) computes 0/0 = NaN, and NaN can sort to the TOP of a ranking, producing a nonsensical "NaN%" in the answer. Always add `WHERE <denominator> > 0` (or `HAVING`) before dividing when ranking BY a computed ratio.
18. ⛔ 'material' IS A CODE, NEVER A NAME. When a follow-up refers to a specific item from the conversation (e.g. "the top item", "that SKU", a name you or the user typed), and you need to filter fact_grn/fact_po/fact_inventory/etc. to it, filter on `material_desc = '<exact name>'` (or ILIKE) — NEVER `material = '<name>'`. material holds a short numeric code ('928038'), so comparing it to a text description matches ZERO rows and produces a false "no data available" even for an item you just showed has plenty of data. If you don't already have the material CODE from an earlier query in this conversation, filter on material_desc directly, or call lookup_item.
19. ⛔ FOLLOW-UP REFINEMENTS MUST KEEP THE PRIOR SCOPE. When the user says "remove X", "exclude Y", "excluding zero/blank ones", "without the outliers", etc. about a list you JUST presented, that is a REFINEMENT of that same list — re-apply every filter the previous query used (category, item type/pharma, entity, time range, etc.) and ONLY add the new exclusion. Rebuilding the query from a broader or different base and silently dropping the earlier scope is a real error (e.g. turning "top PHARMA INJECTION items" into a plain "top items" ranking that now includes hardware/equipment) — it looks like you ignored what was just discussed.
20. ⛔ SCOPED WARNING (do not over-apply this): fact_grn.major_group / fact_grn.minor_group, fact_po.major_group / fact_po.minor_group, AND kpi_purchase_value.category — and ONLY these exact column names on these tables — are RAW, UNCLEANED SOURCE-SYSTEM FIELDS (inconsistent formatting, truncated fragments like "AL NAIL", 1360+ freeform pharmacological-class-style values with NO 'M###-' prefix at all). Never group by THESE for a "category" breakdown, and NEVER apply the material_group prefix-stripping rule (RULES section) to kpi_purchase_value.category — it has no such prefix, and splitting/substringing it (e.g. SUBSTR/SPLIT_PART starting at position 6) produces garbled labels like "HER2)" or blank strings attached to real crore-scale totals. This warning does NOT extend to dim_material.material_group or any table that already carries it (sales_by_material, kpi_stock_value, kpi_doh, kpi_monthly_purchase_value, etc.) — that IS the correct, clean category field, and stripping its 'M###-' prefix + Title-Casing for display (rule in RULES section, e.g. 'M065-INJECTIONS' → 'Injections') is the CORRECT, expected, already-validated way to show it — never second-guess or walk back a material_group-based answer as if it might be the same "raw field" problem; they are unrelated. For ANY category breakdown outside dim_material's own tables, JOIN to dim_material (via kpi_monthly_purchase_value, which already carries material_group, or fact_po/fact_grn JOIN dim_material) and group by material_group instead of the raw fact_grn/fact_po/kpi_purchase_value fields — reserve kpi_purchase_value.category only for a question that specifically needs the vendor×category cross-tab this table alone provides, and even then present its raw value as-is (Title-Case the whole string, don't split it).
21. ⛔ RANKING BY A PERCENTAGE (margin %, markup %, growth %) NEEDS A MATERIALITY FLOOR on the denominator, or tiny/degenerate values dominate the "top" list with a meaningless 100% (e.g. an item with ₹0.30 revenue and ₹0 cost technically has "100% margin" but is not a real finding). Before ranking BY margin_pct/markup, filter to a MEANINGFUL minimum on the base amount (e.g. revenue/spend >= ₹10,000, or rank by the absolute margin VALUE first and only show pct alongside) — never let sub-materiality noise outrank real, high-value results.
22. ⛔ THIS DATASET IS ONLY 6 MONTHS (Dec-2025 … May-2026) STRADDLING TWO CALENDAR YEARS UNEVENLY — "2025" only covers December (1 month), "2026" covers January-May (5 months). Grouping by calendar YEAR (e.g. LEFT(month,4)) and calling the result "year-over-year growth" is deeply misleading — you would be comparing 1 month of revenue to 5 months and presenting the ratio as if it were annual growth. NEVER compute or present a "YoY"/"annual growth" figure this way. If asked for YoY/annual growth, explain plainly that only 6 months of data exist so a true year-over-year comparison isn't possible, and offer month-over-month or the full 6-month trend instead.
23. When a "by category" / "by <dimension>" question has NO "top N" qualifier and the dimension has many distinct values (material_group has 115+), default to a TOP 10 by the relevant measure — same as you already do well for "top vendors"/"top items" without being asked. Do not attempt (or second-guess yourself into re-attempting) a full unranked dump of a 100+-row dimension; a clean top-10 answers the intent and avoids unstable, wobbling SQL rewrites.
24. ⛔ COMPOSITE JOIN KEYS: dim_sloc is keyed by (plant, sloc) TOGETHER, not sloc alone — the same sloc code (e.g. 'S079') is reused by up to 25 different plants. Joining fact_inventory/fact_grn/fact_po to dim_sloc on sloc alone silently multiplies every matching row up to 25x (a ward-type / IP-OP-OT inventory breakdown computed this way can overstate the true total by 10x or more). Always join dim_sloc ON plant AND sloc together — check the GUIDE's join-key listing before joining any dimension table; if it names two key columns together, both must be used.
25. "Which plant / vendor / entity pays the most for X" is a PER-UNIT price question — compare value/qty (or the outlier-cleaned median price from gotcha #15), never raw SUM(spend) or SUM(stock_value) across entities that can legitimately hold very different quantities (e.g. 2 units at one plant vs 300 at another). A raw-total comparison can completely hide a genuine 10-60x per-unit price anomaly for the identical material at different plants — always normalize to a per-unit figure before ranking or comparing prices/costs across entities.
26. fact_po and fact_grn rows with material IS NULL (~27% of PO value) are CAPEX / construction / service / project lines (e.g. "Structural Civil Works", "Solar Electricity Services") — not stocked supply-chain items, and their vendor_name is often a contractor/person, not a supply vendor. Before presenting a "biggest single purchase" / "top item purchased" / similar result, check whether the top row has material IS NULL — if so, either say plainly it's a capex/service line (not a stocked item) alongside the figure, or if the question clearly means supply items, filter to material IS NOT NULL and mention that capex/service POs were excluded.
27. ⛔ MAP THE BUSINESS QUESTION TO THE RIGHT PROCUREMENT SOURCE — don't default to sales/margin for a procurement question:
   • "Are we OVERPAYING?" / "price inconsistency" / "price leakage" / "paying too much" / "which items have inconsistent prices" = a PROCUREMENT PRICE-DISPERSION question. Use mart_material_price_stats — rank by the spread between raw_min_price and raw_max_price (or has_price_outlier / price ratio), NOT sales margin. It is a factual error to answer "are we overpaying" with a top-drugs-by-profit list — profit margin is a SALES metric and says nothing about procurement price dispersion.
   • "Which VENDORS have inconsistent pricing" = rank vendors by how many of their materials show a real price spread. Use mart_procurement (share of a vendor's lines where is_price_outlier is true, among vendors with enough repeat lines) or count materials where that vendor's prices span a wide band — REQUIRE repeat purchases (a vendor that bought one item once cannot be "inconsistent"; don't let single-buy vendors top the list).
   • "CAPITAL vs SUPPLY" / "biggest purchases" / "genuine supply spend excluding capital/service" = classify on fact_po.doc_type: doc_type IN ('Service PO','Dom Capital PO','CMC','AMC','Imp capital PO') OR material IS NULL ⇒ CAPEX/SERVICE (robots, PET-CT, AMC/CMC contracts, civil works — NOT a stocked medical supply); everything else ⇒ SUPPLY. The material-code alone is NOT enough — a ₹7.5 Cr robotic system HAS a material code but is doc_type='Dom Capital PO'. Never call a capital-equipment or service line a "medical supply", and when asked for "supply spend excluding capital" you MUST exclude by doc_type, not just by material-not-null.
28. ⛔ "Risk" / "at risk" / "high risk" questions about INVENTORY touch several DIFFERENT tables that are NOT interchangeable — pick by what's actually asked, and never invent a filter value a column doesn't hold. kpi_risk_classification.risk_level holds real categorical labels ('High'/'Medium'/'Low', driven by batch age + expiry proximity + whether it's ever been consumed — 'High' items are 91%+ never-consumed) — this is the right, general-purpose source for "which items are high/medium/low risk" / "risk level" / a risk classification breakdown. kpi_health_score.health_tier (e.g. 'At Risk'/'Healthy') is for a "health score" / "inventory health" question specifically. stock_replenishment_and_aging_risk has TWO different risk-flavored columns of its own: aging_risk is a REPLENISHMENT-TIMING bucket ('<3 Months', '3-6 Months', '6-12 Months', '1+ Year' — NEVER the string 'High'/'Low'; filtering aging_risk='High' returns 0 rows and produces a false "no high-risk items" answer even though tens of thousands of genuinely high-risk items exist in kpi_risk_classification), while inventory_aging_risk is a plain BOOLEAN (true when aging_risk is '6-12 Months' or '1+ Year' — i.e. a simple "aged 6mo+" slow-mover flag) that remains a fine, narrower source for "how much of our inventory [value] is at risk of going stale" when the question is really about aging/slow-moving stock rather than a High/Medium/Low classification. When a question is ambiguous between these, kpi_risk_classification.risk_level is the safer default for anything phrased as a classification ("which items", "risk level", "high risk") — reach for stock_replenishment_and_aging_risk.inventory_aging_risk only when the question is specifically about replenishment/reorder timing."""

# ── Worked examples (teach the agent good patterns) ─────────────────────────
EXAMPLES = """WORKED EXAMPLES:
Q: Overall / total revenue and margin (the whole company).
SQL: SELECT SUM(revenue) AS revenue, SUM(revenue-cost) AS margin, SUM(revenue-cost)/SUM(revenue)*100 AS margin_pct FROM sales_totals;
-- (canonical total = ₹521.67 Cr. Do NOT use sales_by_manufacturer for this — it undercounts.)

Q: Top manufacturers by revenue and margin.
SQL: SELECT manufacturer, revenue, revenue-cost AS margin, (revenue-cost)/revenue*100 AS margin_pct
     FROM sales_by_manufacturer ORDER BY revenue DESC LIMIT 10;

Q: Which manufacturers have stock expiring within 90 days, by value?
SQL: SELECT m.manufacturer_desc AS manufacturer, sum(i.total_cost) AS expiring_value, count(DISTINCT i.material) AS items
     FROM fact_inventory i JOIN dim_material m ON i.material=m.material
     WHERE i.qty>0 AND i.expiry_date IS NOT NULL
       AND date_diff('day', DATE '2026-05-31', i.expiry_date) BETWEEN 0 AND 90
     GROUP BY 1 ORDER BY expiring_value DESC LIMIT 10;

Q: For items expiring in 90 days, did we overpay vs the median purchase price? / Which items have the biggest price deviation impact? / Biggest price increases?
Any of these needs the outlier-clean two-pass pattern (gotcha #15) — a first-pass median to find each material's normal price, then drop rows that stray outside an 8x band (data-entry/UOM errors), THEN compute the real metric from the clean rows only:
SQL: WITH raw AS (SELECT * FROM fact_grn WHERE net_price>=10 AND gr_qty>0),
     pass1 AS (SELECT material, median(net_price) AS m1 FROM raw GROUP BY 1),
     clean AS (SELECT r.* FROM raw r JOIN pass1 p USING(material) WHERE r.net_price BETWEEN p.m1/8.0 AND p.m1*8.0),
     med AS (SELECT material, median(net_price) AS med_price, count(*) AS n FROM clean GROUP BY 1 HAVING count(*)>=5)
     SELECT g.material, any_value(g.material_desc) AS item, sum(abs(g.net_price-med.med_price)*g.gr_qty) AS price_deviation_impact
     FROM clean g JOIN med USING(material) GROUP BY 1 ORDER BY price_deviation_impact DESC LIMIT 10;
-- For "did we overpay" specifically (one-directional), swap the final SUM to sum(greatest(g.net_price-med.med_price,0)*g.gr_qty) — still built on the same outlier-clean `clean`/`med` CTEs, never on raw fact_grn directly.

Q: Which plant pays the most for <item X>? / Compare price across plants.
Use mart_procurement's per-unit price — never rank by raw SUM(spend) (different plants buy different quantities, so totals aren't comparable — gotcha #25). For a SINGLE named item's cross-plant/vendor comparison, do NOT filter out is_price_outlier — the anomalous plant IS usually the point of the question; instead SHOW every plant and surface the flag/quantity so the reader can judge:
SQL: SELECT plant, median(unit_price) AS unit_price, sum(qty) AS qty, bool_or(is_price_outlier) AS looks_anomalous
     FROM mart_procurement WHERE material = '<code>' GROUP BY plant ORDER BY unit_price DESC;
-- If the top plant is flagged looks_anomalous on a tiny qty (e.g. ₹2,269/unit on 2 units vs ₹37 elsewhere), REPORT it as the headline but caveat it — "HM04 is paying ~60x more per unit, though on only 2 units, which may be a data/UOM issue worth checking" — that anomaly is exactly what a procurement manager wants surfaced, not hidden.
-- (Filtering out is_price_outlier is only right when RANKING MANY items where a single fake outlier would produce a garbage headline number — not for inspecting one named item across plants.)

Q: Which vendor is cheapest for <item X>? / How much could we save by consolidating to the best-priced vendor?
Use mart_material_vendor_price_stats and ONLY trust vendors with a stable price (clean_n>=5) — a 2-3 line "cheap" vendor is a data-entry outlier, not an achievable price (this is exactly the trap that produces an embarrassing fake "₹X Cr savings" number):
SQL: SELECT vendor_name, clean_median_price, clean_n, total_qty
     FROM mart_material_vendor_price_stats WHERE material = '<code>' AND price_is_stable ORDER BY clean_median_price ASC;
-- For a portfolio-wide savings estimate, compute per material: (current_weighted_price − cheapest_STABLE_vendor_price) * qty, summing ONLY over materials that HAVE a stable cheaper alternative — never let an n=3 outlier vendor set the "achievable" price.

Q: Are we overpaying for anything? / Which items have the most inconsistent purchase prices? (price-dispersion audit — NOT a margin question)
SQL: SELECT material_desc, category, clean_median_price, clean_min_price, clean_max_price, clean_n,
            clean_price_spread, clean_max_price / NULLIF(clean_min_price, 0) AS price_ratio
     FROM mart_material_price_stats
     WHERE clean_n >= 5 AND clean_median_price >= 100
     ORDER BY clean_price_spread DESC LIMIT 10;
-- Rank by clean_price_spread (dispersion WITHIN the clean band — the genuine over/under-pay signal). Do NOT gate on has_price_outlier: that is a 20x flag for gross data-entry errors, and real overpayment dispersion runs ~2-5x, so it wrongly returns ZERO and falsely reassures "we're not overpaying". Add "AND category ILIKE '%injection%'" (or the right material_group) to scope to a drug type. This surfaces items whose paid price genuinely swings (e.g. BEVACIREL ₹8,050→₹39,000, MABTAS ₹6,500→₹30,450). NEVER answer this with a top-drugs-by-profit / margin ranking. (clean_price_spread is an absolute ₹ amount, so a high-value drug with a big spread ranks first — that's usually the intent; if the user wants proportional swings, sort by price_ratio instead.)

Q: Which vendors have the most inconsistent pricing? (rank vendors by real price dispersion)
SQL: SELECT vendor_name, count(*) AS outlier_lines, count(DISTINCT material) AS items,
            sum(CASE WHEN is_price_outlier THEN 1 ELSE 0 END) AS flagged
     FROM mart_procurement
     GROUP BY vendor_name HAVING count(*) >= 20 AND sum(CASE WHEN is_price_outlier THEN 1 ELSE 0 END) > 0
     ORDER BY flagged DESC LIMIT 10;
-- REQUIRE repeat volume (HAVING count(*) >= 20) so a vendor that bought one item once can't be called "inconsistent". price_is_stable=FALSE means "too few orders to judge", NOT "inconsistent" — don't conflate the two.

Q: Capital vs supply split / biggest purchases / genuine supply spend excluding capital & service.
SQL: SELECT CASE WHEN doc_type IN ('Service PO','Dom Capital PO','CMC','AMC','Imp capital PO') OR material IS NULL
                 THEN 'Capex/Service' ELSE 'Supply' END AS spend_type,
            count(*) AS lines, sum(total_value_wo_tax) AS value
     FROM fact_po GROUP BY 1;
-- "genuine supply spend" = the Supply row only. A robotic system / PET-CT / AMC contract is Capex/Service even if it has a material code (classify by doc_type, never by material-not-null alone).

Q: What's the purchase price of <named item X>? (single-item lookup)
SQL: SELECT material_desc, clean_median_price, raw_n FROM mart_material_price_stats WHERE material_desc ILIKE '%X%';
-- Report clean_median_price with "based on raw_n purchase records"; if raw_n is small, add a light caveat — but NEVER refuse ("could not be determined") just because clean_n<5. The price is knowable from however many records exist.

Q: Portfolio days of cover.
SQL: SELECT median(doh_days) AS median_doh FROM kpi_doh WHERE doh_days>0;

Q: Top vendors by spend (dedup across plants).
SQL: SELECT vendor_name, sum(vendor_value) AS spend FROM kpi_vendor_volume GROUP BY 1 ORDER BY spend DESC LIMIT 10;

Q: Spend on pharma / a physical category (injections, tablets, etc.) — e.g. "total spend on pharma injection items".
kpi_purchase_value CANNOT do this (no material/material_type column — see GUIDE). Go through fact_po JOIN dim_material instead:
SQL: SELECT SUM(p.total_value_wo_tax) AS spend
     FROM fact_po p JOIN dim_material m ON p.material = m.material
     WHERE m.material_type IN ('ZNOC-Medical Non Onco Drugs','ZOC-Medical Onco Drugs')
       AND m.material_group ILIKE '%injection%'
       AND p.po_date >= DATE '2025-12-01' AND p.po_date < DATE '2026-06-01';
-- (material_group ILIKE, not an exact '=', since the stored value is 'M065-INJECTIONS'; never filter kpi_purchase_value.category for this.)

Q: Has monthly procurement spend variance improved? / By how much did spend change this month?
Never AVG(a precomputed variance_pct column) across plants (gotcha #4) — recompute the real, weighted change from the raw sums:
SQL: SELECT year, month, SUM(purchase_value) AS spend, SUM(prev_value) AS prev_spend,
            (SUM(purchase_value)-SUM(prev_value))/NULLIF(SUM(prev_value),0)*100 AS true_variance_pct
     FROM kpi_procurement_variance GROUP BY year, month ORDER BY <chronological CASE on month, per gotcha #6>;
-- Do NOT also report AVG(variance_pct) alongside this — it's the exact unweighted-mean trap that produces a nonsensical figure like "+247.6%" next to a true "+10.8%" in the same answer.

Q: "Does <item X> have any sales/purchase activity?" and sales_by_material + fact_po + fact_grn all return 0 rows.
Before answering "no data", ALSO check physical inventory (don't stop at sales/purchase):
SQL: SELECT plant, qty, total_cost, aging_days, expiry_date, formulary FROM fact_inventory WHERE material = '<code>' AND qty > 0;
If this returns rows: it's NOT a data gap — it's dead/non-moving stock. Report the qty, how long it's been aging, whether expiry_date is already past the 2026-05-31 snapshot, and the formulary flag (OUT OF FORMULARY commonly explains why it stopped moving). Only say "no data at all" if inventory is ALSO empty."""


def context() -> str:
    return (
        "LIVE SCHEMA (view [rows]: col:type):\n" + warehouse.schema_text()
        + "\n\nDIMENSIONAL MODEL — for each table, the dimensions you may slice by and whether it has a time axis. "
          "A figure is only 'about' a dimension if the query GROUPed/filtered a table that carries it. NEVER attribute a "
          "table's numbers to a dimension not in its 'slice by' list, and never show a time trend from a table whose time axis is NONE:\n"
        + warehouse.grain_text()
        + "\n\n" + RULES + "\n\n" + GUIDE + "\n\n" + GOTCHAS + "\n\n" + EXAMPLES
    )
