

UI_COLUMN_MAP = { "KPI_1":
                    {
                        "materialId": "[Material]",
                        "materialName": "[Material Description]",
                        "materialGroup": "[Material Group]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "stockChange": "[Stock Change]",
                    },
                    "KPI_2":{
                        "materialId": "[Material ID]",
                        "materialName": "[Material Name]",
                        "materialGroup": "[Material Group]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "inventoryValuation": "[Inventory Valuation]",
                    },
                    "KPI_3":{
                        "materialId": "[Material ID]",
                        "materialName": "[Material Name]",
                        "materialGroup": "[Material Group]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "cogs": "[COGS]",
                        "averageInventoryValue": "[Avg Inventory Value]",
                        "inventoryTurnOverRatio": "[ITR]",
                    },
                    "KPI_4":{
                        "materialId": "[Material ID]",
                        "materialName": "[Material Name]",
                        "materialGroup": "[Material Group]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "soldUnits": "[Sold Units]",
                        "returnedUnits": "[Returned Units]",
                        "returnRate": "[Return Rate (%)]",
                    },
                    "KPI_5":{
                        "materialId": "[Material ID]",
                        "materialName": "[Material Name]",
                        "ageSinceLastSale": "[Age Since Last Sale (days)]",
                        "ageSinceLastPurchase": "[Age Since Last Purchase (days)]",
                        "aging": "[Aging]",
                    },
                    "KPI_6":{
                        "materialId": "[Material ID]",
                        "materialName": "[Material Name]",
                        "materialGroup": "[Material Group]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "monthlyPurchaseValue": "[Monthly Purchase Value]",
                    },
                    "KPI_7":{
                        "vendorName": "[Vendor Name]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "totalVolume": "[GRN Volume]",
                        "averageUnitCost": "[Unit Purchase Price]",
                        "sellingPrice": "[Unit MRP Price]",
                        "margin":"[Unit Margin]"
                    },
                    "KPI_8":{
                        "materialId": "[Material ID]",
                        "materialName": "[Material Name]",
                        "materialGroup": "[Material Group]",
                        "year": "[Year]",
                        "period": "[Month]",
                        "totalUnitsSold": "[Total Units Sold]",
                    },
                    "KPI_9":{
                        "year": "[Year]",
                        "period": "[Month]",
                        "opSales": "[OP Sales]",
                        "ipIssue": "[IP Issue]",
                        "internalConsumption": "[Internal Consumption]",
                    },
                }